// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZSk8VIfOnrpcZr-PbZs05ACfkEFZKzOE',
    appId: '1:262056834582:web:f044e194ab33557f4ca737',
    messagingSenderId: '262056834582',
    projectId: 'denuncias-salcedo-18df4',
    authDomain: 'denuncias-salcedo-18df4.firebaseapp.com',
    storageBucket: 'denuncias-salcedo-18df4.firebasestorage.app',
    measurementId: 'G-3RDHD48KHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdnAlKlUQi7TDo7xzeLl6VSsJ29Sqwgw',
    appId: '1:262056834582:android:e5d0fe32406a106a4ca737',
    messagingSenderId: '262056834582',
    projectId: 'denuncias-salcedo-18df4',
    storageBucket: 'denuncias-salcedo-18df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4oA4rcR_SvXs_7euha95Lw1LukLGiQZU',
    appId: '1:262056834582:ios:529a23668f776e4c4ca737',
    messagingSenderId: '262056834582',
    projectId: 'denuncias-salcedo-18df4',
    storageBucket: 'denuncias-salcedo-18df4.firebasestorage.app',
    iosBundleId: 'com.example.appMovilDenuncias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4oA4rcR_SvXs_7euha95Lw1LukLGiQZU',
    appId: '1:262056834582:ios:529a23668f776e4c4ca737',
    messagingSenderId: '262056834582',
    projectId: 'denuncias-salcedo-18df4',
    storageBucket: 'denuncias-salcedo-18df4.firebasestorage.app',
    iosBundleId: 'com.example.appMovilDenuncias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZSk8VIfOnrpcZr-PbZs05ACfkEFZKzOE',
    appId: '1:262056834582:web:5111765844830c594ca737',
    messagingSenderId: '262056834582',
    projectId: 'denuncias-salcedo-18df4',
    authDomain: 'denuncias-salcedo-18df4.firebaseapp.com',
    storageBucket: 'denuncias-salcedo-18df4.firebasestorage.app',
    measurementId: 'G-RFH5E4SN15',
  );
}
